driver:
  name: vagrant
  ssh:
    insert_key: false
  customize:
    memory: 2048
    cpus: 2

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
- name: centos-6.6

suites:
- name: standalone
  run_list:
    - recipe[test::hostsfile]
    - recipe[test::setup_ssh_keys]
    - recipe[chef-server]
    - recipe[chef-server::addons]
    - recipe[test::user_and_org]
  driver:
    vm_hostname: chef.example.com
    network:
      - ['private_network', {ip: '33.33.33.10'}]
  attributes:
    chef-server:
      api_fqdn: 'chef.example.com'
      analytics:
        fqdn: 'analytics.example.com'
      addons:
        - opscode-manage
        - opscode-reporting
        - opscode-push-jobs-server
      configuration:
        oc_id:
          applications:
            analytics:
              redirect_uri: 'https://analytics.example.com/'
        rabbitmq:
          vip: '33.33.33.10'
          node_ip_address: '0.0.0.0'

- name: standalone-analytics
  run_list:
  - recipe[test::hostsfile]
  - recipe[test::replicate_opscode_analytics]
  - recipe[chef-server::analytics]
  driver:
    vm_hostname: analytics.example.com
    network:
      - ['private_network', {ip: '33.33.33.11'}]
  attributes:
    chef-server:
      api_fqdn: 'chef.example.com'
      analytics:
        fqdn: 'analytics.example.com'

- name: tiered-backend
  run_list:
  - recipe[test::hostsfile]
  - recipe[test::setup_ssh_keys]
  - recipe[chef-server]
  - recipe[chef-server::addons]
  - recipe[test::user_and_org]
  driver:
    vm_hostname: backend.example.com
    network:
      - ['private_network', {ip: '33.33.33.12'}]
  attributes:
    chef-server:
      topology: 'tier'
      api_fqdn: 'frontend.example.com'
      analytics:
        fqdn: 'tiered-analytics.example.com'
      addons:
        - opscode-reporting
        - opscode-push-jobs-server
      configuration:
        oc_id:
          applications:
            analytics:
              redirect_uri: 'https://tiered-analytics.example.com/'
        rabbitmq:
          vip: '33.33.33.12'
          node_ip_address: '0.0.0.0'
      servers:
        - 
          fqdn: backend.example.com
          ipaddress: 33.33.33.12
          bootstrap: true
          role: 'backend'
        - 
          fqdn: frontend.example.com
          ipaddress: 33.33.33.13
          role: 'frontend'

- name: tiered-frontend
  run_list:
  - recipe[test::hostsfile]
  - recipe[test::replicate_etc_opscode]
  - recipe[chef-server::frontend]
  - recipe[chef-server::addons]
  driver:
    vm_hostname: frontend.example.com
    network:
      - ['private_network', {ip: '33.33.33.13'}]
  attributes:
    chef-server:
      analytics:
        fqdn: 'tiered-analytics.example.com'
      addons:
        - opscode-manage
        - opscode-reporting
        - opscode-push-jobs-server

- name: tiered-analytics
  run_list:
  - recipe[test::hostsfile]
  - recipe[test::replicate_opscode_analytics]
  - recipe[chef-server::analytics]
  driver:
    vm_hostname: tiered-analytics.example.com
    network:
      - ['private_network', {ip: '33.33.33.14'}]
  attributes:
    chef-server:
      topology: 'tier'
      api_fqdn: 'frontend.example.com'
      analytics:
        fqdn: 'tiered-analytics.example.com'
