driver:
  name: vagrant
  ssh:
    insert_key: false
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
- name: centos-6.6

suites:
- name: standalone
  run_list:
    - recipe[test::hostsfile]
    - recipe[chef-server]
    - recipe[chef-server::addons]
    - recipe[test::user_and_org]
  driver:
    vm_hostname: chef.example.com
    network:
      - ['private_network', {ip: '33.33.33.10'}]
  attributes:
    chef-server:
      api_fqdn: 'chef.example.com'
      addons:
        - opscode-manage

- name: tiered-backend
  run_list:
  - recipe[test::hostsfile]
  - recipe[test::setup_ssh_keys]
  - recipe[chef-server]
  - recipe[chef-server::addons]
  driver:
    vm_hostname: backend.example.com
    network:
      - ['private_network', {ip: '33.33.33.12'}]
  attributes:
    chef-server:
      topology: 'tier'
      api_fqdn: 'frontend.example.com'
      servers:
        - 
          fqdn: backend.example.com
          ipaddress: 33.33.33.12
          bootstrap: true
          role: 'backend'
        - 
          fqdn: frontend.example.com
          ipaddress: 33.33.33.13
          role: 'frontend'

- name: tiered-frontend
  run_list:
  - recipe[test::hostsfile]
  - recipe[test::replicate_etc_opscode]
  - recipe[chef-server::frontend]
  - recipe[chef-server::addons]
  - recipe[test::user_and_org]
  driver:
    vm_hostname: frontend.example.com
    network:
      - ['private_network', {ip: '33.33.33.13'}]
  attributes:
    chef-server:
      addons:
        - opscode-manage
