driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_zero

platforms:
- name: ubuntu-14.04
- name: centos-6.6

suites:
- name: standalone
  run_list:
    - recipe[test::hostsfile]
    - recipe[chef-server]
    - recipe[chef-server::addons]
  driver:
    vm_hostname: chef.example.com
    network:
      - ['private_network', {ip: '33.33.33.10'}]
  attributes:
    chef-server:
      api_fqdn: 'chef.example.com'
      addons:
        - opscode-manage

